services:
  - type: web
    name: silent-discord
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: silent-db
          property: connectionString
      - key: DISCORD_BOT_TOKEN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free

databases:
  - name: silent-db
    databaseName: silent
    user: silent
    plan: free